# ES访问地址和端口
es_host: "http://118.118.118.162:9200/" # 贵州环境
# es_host: "127.0.0.1:9200"
es_index: "jg_liuliang*"
es_user: "elastic"
es_password: "admin123"
# 查询时间范围（单位/天）
es_timerange: 30

# Mysql访问地址和端口
mysql_host: "108.108.108.155" # 贵州环境
# mysql_host: "127.0.0.1"
mysql_user: "root"
mysql_password: "Fff123123"
mysql_database: "data-storage"


# 数据名称
sql_data: "mysql.csv"
es_data: "es.csv"
# 原始数据存储路径
ori_data_dic: "Ori_Data/"
# 清洗数据存储路径
cleaned_data_dic: "Cleaned_Data/"
# 训练模型存储路径
model_save_path: "Rnn_Model/"


# 应用分类模块
app_traffic_data: "app_traffic/app_traffic.csv"
